apiVersion: apps/v1
kind: Deployment
metadata:
    name: expensify-front
spec:
    replicas: 3
    selector:
        matchLabels:
            app: expensify-front
    template:
        metadata:
            labels:
                app: expensify-front
        spec:
            containers:
            -   name: expensify-front
                image: rmk8sacr.azurecr.io/expensify-front:v1
                ports:
                -   containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: expensify-front
spec:
    selector:
        app: expensify-front
    type: LoadBalancer
    ports:
    -   port: 80
    